apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rabbitmq-selfsigned
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selfSigned: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    cert-manager.io/issuer: rabbitmq-selfsigned
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: rabbitmq
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rabbitmq.smartops.space
      secretName: rabbitmq-management-tls
  rules:
    - host: rabbitmq.smartops.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  name: management
