apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BunathPheng/Rabbit_MQ_Mainifestfile.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/volumeClaimTemplates
